# Generated by Django 5.1.1 on 2024-10-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='name',
            new_name='item',
        ),
    ]
