# Generated by Django 5.1.1 on 2024-10-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='app.customer'),
        ),
    ]
