# Generated by Django 5.1.1 on 2024-10-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
