# Generated by Django 5.0 on 2024-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_dispensinglog_amount_alter_dispensinglog_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='dispensinglog',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispensinglog',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
