# Generated by Django 5.1.1 on 2024-10-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customer_address_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
