# Generated by Django 5.1.1 on 2024-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
