# Generated by Django 5.1.1 on 2024-10-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_transactionhistory_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='app.sales')),
            ],
        ),
    ]
