# Generated by Django 5.1.1 on 2024-10-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_receipt_printed_receipt_receipt_short_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_short_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
