# Generated by Django 5.1.1 on 2024-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_receipt_receipt_short_id_receipt_printed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
