# Generated by Django 5.0 on 2024-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='unit',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
