# Generated by Django 5.1.1 on 2024-11-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_item_markup_percentage_wholesale_markup_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wholesale')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleSalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wholesale')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_sales_items', to='app.sales')),
            ],
        ),
    ]
