# Generated by Django 5.1.1 on 2024-11-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_wholesalesalesitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
