# Generated by Django 5.1.1 on 2024-11-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_wholesale_unit_alter_wholesalecartitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='unit',
            field=models.CharField(default='unit', max_length=10),
        ),
    ]
