# Generated by Django 5.1.1 on 2024-11-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_wholesalecustomer_wholesalecustomerwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalecustomerwallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_customer_wallet', to='app.wholesalecustomer'),
        ),
    ]
