# Generated by Django 5.1.1 on 2024-11-10 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_transactionhistory_wholesale_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wholesalecustomer'),
        ),
    ]
