# Generated by Django 5.1.1 on 2024-11-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_receipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='wholesale_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wholesalecustomer'),
        ),
    ]
