# Generated by Django 5.1.1 on 2024-11-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_receipt_wholesale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.sales'),
        ),
    ]
