# Generated by Django 5.1.1 on 2024-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_item_markup_percentage_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('unit', 'Select Unit'), ('PCS', 'Pieces'), ('TAB', 'Tablets'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ample'), ('VAIL', 'Vail')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='unit',
            field=models.CharField(choices=[('unit', 'Select Unit'), ('PCS', 'Pieces'), ('TAB', 'Tablets'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ample'), ('VAIL', 'Vail')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='wholesalecartitem',
            name='unit',
            field=models.CharField(choices=[('unit', 'Select Unit'), ('PCS', 'Pieces'), ('TAB', 'Tablets'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ample'), ('VAIL', 'Vail')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='wholesalesalesitem',
            name='unit',
            field=models.CharField(choices=[('unit', 'Select Unit'), ('PCS', 'Pieces'), ('TAB', 'Tablets'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ample'), ('VAIL', 'Vail')], default='unit', max_length=10),
        ),
    ]
