# Generated by Django 5.1.1 on 2024-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_cartitem_unit_alter_dispensinglog_quantity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('sales',), name='unique_sales_receipt'),
        ),
    ]
