# Generated by Django 5.1.1 on 2024-11-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_receipt_sales_alter_salesitem_sales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='receipt',
            name='unique_sales_receipt',
        ),
    ]
