# Generated by Django 5.1.1 on 2024-11-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_receipt_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Partially Returned', 'Partially Returned'), ('Dispensed', 'dispensed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='app.sales'),
        ),
    ]
