# Generated by Django 5.1.1 on 2024-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_dispensinglog_status_alter_salesitem_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Partially Returned', 'Partially Returned'), ('Dispensed', 'dispensed')], default='dispensed', max_length=20),
        ),
    ]
