# Generated by Django 5.1.1 on 2024-11-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_dispensinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensinglog',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Partially Returned', 'Partially Returned'), ('Dispensed', 'Dispensed')], default='Dispensed', max_length=20),
        ),
    ]
