# Generated by Django 5.1.1 on 2024-11-24 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_dispensinglog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='wholesale_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wholesalecustomer'),
        ),
    ]
