# Generated by Django 5.0 on 2024-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_sales_wholesale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Wallet', 'Wallet'), ('Transfer', 'Transfer')], default='Cash', max_length=20),
        ),
    ]
