# Generated by Django 5.0 on 2024-12-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_wholesalereceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='wholesale_customer',
        ),
    ]
