# Generated by Django 5.1.1 on 2024-12-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_procureditem_unit_alter_cartitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procureditem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('TAB', 'Tablets'), ('CARD', 'Cards'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ampules'), ('VAIL', 'Vial')], default='PCS', max_length=10),
        ),
    ]
