# Generated by Django 5.1.1 on 2024-12-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_procureditem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='receipts', to='app.procureditem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.supplier')),
            ],
        ),
    ]
