# Generated by Django 5.1.1 on 2024-12-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_procurementreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementreceipt',
            name='items',
        ),
        migrations.AlterField(
            model_name='procurementreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procure_receipts', to='app.supplier'),
        ),
    ]
