# Generated by Django 5.1.1 on 2024-12-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_remove_procurementreceipt_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procureditem',
            name='procurement_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='procurementreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_receipts', to='app.supplier'),
        ),
    ]
