# Generated by Django 5.1.1 on 2024-12-13 21:00

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_procureditem_procurement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementreceipt',
            name='receipt_date',
        ),
        migrations.AddField(
            model_name='procurementreceipt',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Transfer', 'Transfer')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementreceipt',
            name='procurement_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='procurementreceipt',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurementreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
        migrations.CreateModel(
            name='ProcurementCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('unit', 'Select Unit'), ('PCS', 'Pieces'), ('TAB', 'Tablets'), ('CARD', 'Cards'), ('TIN', 'Tins'), ('BTL', 'Bottles'), ('PCK', 'Packets'), ('ROLL', 'Rolls'), ('CTN', 'Cartons'), ('AMP', 'Ampules'), ('VAIL', 'Vail')], default='unit', max_length=10)),
                ('quantity', models.IntegerField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procureditem')),
            ],
        ),
    ]
