# Generated by Django 5.1.1 on 2024-12-13 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_remove_procurementreceipt_receipt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procureditem',
            name='procurement_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wholesalereceipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
