# Generated by Django 5.1.1 on 2024-12-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procureditem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
