# Generated by Django 5.1.1 on 2024-12-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_remove_procurementcartitem_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcartitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procurementcartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
