# Generated by Django 5.1.1 on 2024-12-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_alter_procurementcartitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementcartitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.procureditem'),
        ),
        migrations.AlterField(
            model_name='procurementcartitem',
            name='procurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app.procurement'),
        ),
    ]
