# Generated by Django 5.1.1 on 2024-12-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_procureditem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='ProcuredItem',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
    ]
