# Generated by Django 5.1.1 on 2024-12-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_procurementitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.procurement'),
        ),
    ]
