# Generated by Django 5.1.1 on 2024-12-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_alter_procurement_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='receipt_id',
        ),
    ]
