# Generated by Django 5.1.1 on 2024-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_activitylog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='brand',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
