# Generated by Django 5.1.1 on 2024-12-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_item_brand_wholesale_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='brand',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
