# Generated by Django 5.1.1 on 2024-12-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_itemselectionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemselectionhistory',
            name='user',
        ),
    ]
