# Generated by Django 5.1.1 on 2024-12-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_wholesaleselectionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleselectionhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wholesale'),
        ),
    ]
