# Generated by Django 5.1.1 on 2024-12-21 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_alter_wholesaleselectionhistory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselectionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wholesaleselectionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
