# Generated by Django 5.1.1 on 2024-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_alter_itemselectionhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemselectionhistory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wholesaleselectionhistory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
