# Generated by Django 5.1.1 on 2024-12-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_alter_procurementitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementitem',
            name='brand',
            field=models.CharField(blank=True, default='Brand', max_length=225, null=True),
        ),
    ]
